#!/usr/bin/python3

###### IMPORTS
import socket
import argparse
from urllib.parse import urlparse
import re
import ipaddress
################################################################################


###### CONSTANTS
CONST_LOGIN = 'xhaisl00'
################################################################################


###### FUNCTION DEFINITIONS
def constructWHEREIS(hostname):
  return "WHEREIS " + str(hostname)

def constructGET(path, hostname):
  request = "GET "+path+" FSP/1.0\r\n"
  request += "Hostname: "+hostname+"\r\n"
  request += "Agent: "+CONST_LOGIN+"\r\n\r\n"
  return request
################################################################################


###### READ ARGUMENTS FROM STDIN
argParser = argparse.ArgumentParser()
argParser.add_argument(
    "-n", required=True, nargs=1, help="IP address of server"
  )
argParser.add_argument(
    "-f", required=True, nargs=1, help="Address to download from"
  )
args = vars(argParser.parse_args())
#print("Arg1: "+str(args["n"][0]))
#print("Arg2: "+str(args["f"][0]))
#print("")
################################################################################


###### RESOLVE IP IN FIRST ARGUMENT
fstIP = ""
try:
  fstIP = ipaddress.ip_address(str(args['n'][0]))
except ValueError:
  print("Invalid IP address given, exiting...")
  exit(1)
#print(fstIP)
#print("")
################################################################################


###### RESOLVE FSP SERVER ADDRESS
if args['f'][0][0:6].lower() != "fsp://":
  print("Invalid server protocol, use 'fsp://', exiting...")
  exit(1)

firstSlashPos = args['f'][0][6:].find('/')
hostname = args['f'][0][6:firstSlashPos+6]
path = args['f'][0][7+firstSlashPos:]

if path == "":
  print("Invalid path to file, exiting...")
  exit(1)
################################################################################


###### RESOLVE IP IN DNS
print(constructWHEREIS(hostname))
print("")
################################################################################

###### RESOLVE IP IN DINS
print(constructGET("kek", hostname))
################################################################################